### ISSUE TITLE
Add .gitignore and remove untracked data

### ISSUE THREAD

**Issue by yamasakih** [rdkit-users-jp/UGMJP2020#8]
cf. https://github.com/github/gitignore/blob/master/Jekyll.gitignore

**Comment by yamasakih** [comment]
`git rm _site/*` because files in `_site`are not needed to build web page.

**Comment by yamasakih** [comment]
Oops, `_site` directory and files in it are need for build except of default theme in Github Page.

**Comment by kubor** [comment]
done with #33
